# -*- coding: utf-8 -*-
"""Contenu de l'audit YAHRIA BUSINESS OS V1 — Partie C (chapitres 7 à 9)."""

CH7 = [
    {"t": "h1", "x": "7. Incohérences structurelles et angles morts"},
    {"t": "p", "x": "Au-delà des risques externes, l'audit relève six tensions internes au design — des incohérences qui ne relèvent pas de l'erreur mais de choix non encore arbitrés, et qui devront être tranchées avant l'écriture du premier lot de code, car chacune conditionne l'architecture d'un composant central."},
    {"t": "h2", "x": "7.1 Seize agents, une seule chaîne de pouvoirs"},
    {"t": "p", "x": "Le document décrit une seule séquence de validation — intent, policy, autorisation, risque, approbation — sans spécifier sa granularité : qui approuve quoi, selon quels plafonds, dans quels délais, avec quelles délégations et quelles exceptions. Sans matrice de délégation explicite, l'approbation humaine deviendra l'un ou l'autre de deux échecs symétriques : un goulot d'étranglement où tout escalade vers le dirigeant, ou une façade où tout s'auto-approuve par lassitude. Le document doit définir des seuils par type d'agent, par montant et par période, ainsi que les rôles habilités à déléguer — c'est autant une question de design produit que de sécurité."},
    {"t": "h2", "x": "7.2 Un marketplace avant un écosystème"},
    {"t": "p", "x": "L'effet de réseau que le marketplace suppose se construit après les utilisateurs, pas avant. Le design technique des extensions (API, bus d'événements, politiques) est le bon et mérite d'être figé dès maintenant comme contrainte ; la brique commerciale, elle, n'a de sens qu'avec une base installée. La séquence correcte est : clients, API stable, partenaires d'intégration, puis marketplace. La séquence inverse exposerait un catalogue vide, dont le signal perçu est la faiblesse de l'écosystème plutôt que son ouverture."},
    {"t": "h2", "x": "7.3 Des Sector Engines qui « réutilisent tout » — mécanisme non spécifié"},
    {"t": "p", "x": "Le document affirme que chaque engine réutilise le noyau et ajoute ses entités, workflows, règles et indicateurs, sans jamais spécifier le mécanisme d'extension : comment un engine ajoute-t-il une entité sans modifier le schéma du Core ? Comment injecte-t-il des règles sans forker les moteurs ? C'est LE point technique qui décidera si treize engines coûtent treize produits ou treize configurations. L'arbitrage recommandé : un mécanisme déclaratif d'extension (entités, règles, workflows, indicateurs décrits dans des manifestes chargés par le noyau), testé sur le premier engine pilote, avant tout engagement sur les douze autres."},
    {"t": "h2", "x": "7.4 Des Country Packs sans plan de partenariats"},
    {"t": "p", "x": "Les packs listent « Banking, Mobile Money, Payment Providers, Government APIs » comme composants, mais le document ne dit rien des accords commerciaux et techniques que ces composants supposent : agrégateurs de paiement, banques, régulateurs, passerelles gouvernementales. Or c'est la partie la plus déterminante de la roadmap YAHRIA — et elle n'est pas logicielle. Chaque pays pilote devrait être précédé d'un mini-plan de partenariats avec responsables, délais et plans de repli ; sans cela, les délais des Country Packs seront dictés par des tiers, non par l'équipe."},
    {"t": "h2", "x": "7.5 L'absence du modèle économique"},
    {"t": "p", "x": "Pour un document d'une telle exhaustivité technique, le silence sur le segment, le prix, le canal et le coût d'acquisition est l'angle mort le plus significatif de l'ensemble. Ce n'est pas un chapitre manquant : c'est la variable qui devrait ordonner toutes les autres. Le choix du segment d'ancrage détermine quel sector engine vient en premier ; la structure de coûts de la boucle evidence (stockage, inférence, intégrations) détermine quel pricing est viable ; le canal — cabinets comptables partenaires, intégrateurs, vente directe — détermine quelles API viennent avant les autres. L'audit recommande de traiter ce chapitre comme un prérequis de la V1, au même titre que l'architecture."},
    {"t": "h2", "x": "7.6 Pas de stratégie de connectivité dégradée"},
    {"t": "p", "x": "Un système d'exploitation « pour l'entreprise africaine » qui ne mentionne ni mode hors ligne, ni resynchronisation, ni conception à faible bande passante présente une incohérence entre sa promesse de marché et son architecture. Les coupures et la latence sont des conditions normales d'exploitation sur une partie du continent. L'audit recommande d'intégrer dès la V1 une capture dégradée (file locale, resynchronisation avec détection de conflits) au moins pour les fonctions de saisie — facture, dépense, encaissement — qui constituent le flux vital des données."},
    {"t": "quote", "x": "Le différenciateur n'est pas de savoir si YAHRIA peut tout lister ; il est de savoir ce que YAHRIA livrera d'abord, à qui, et comment on en prouvera la valeur."},
]

CH8 = [
    {"t": "h1", "x": "8. Verdict : le périmètre V1 viable"},
    {"t": "h2", "x": "8.1 Le principe directeur : la boucle, pas le catalogue"},
    {"t": "p", "x": "Le principe qui gouverne toutes les recommandations de cet audit tient en une phrase : la V1 doit démontrer la boucle complète en petit — opération captée, preuve produite, graphe enrichi, réponse intelligente avec référence de preuve — plutôt que de déployer un catalogue large où la boucle reste superficielle. Une V1 qui exécute parfaitement le cycle « facture, encaissement, écriture comptable, preuve, question du dirigeant avec réponse sourcée » sur deux pays et un secteur vaut stratégiquement infiniment plus qu'une plateforme à dix domaines dont aucun n'est éprouvé. Elle crée l'actif qui compose ensuite : des données propres, une chaîne de preuve éprouvée, un graphe de qualité croissante."},
    {"t": "h2", "x": "8.2 Le périmètre recommandé"},
    {"t": "table", "title": "Tableau 6 — Périmètre V1 recommandé : figer, construire en lecture seule, différer", "widths": [0.24, 0.76],
     "header": ["Catégorie", "Contenu"],
     "aligns": ["l", "l"],
     "rows": [
        ["Figer en V1", "Core réduit (10-12 entités, invariants complets) ; Money (orchestration, idempotence, réconciliation, ledger interne, deux fournisseurs par pays) ; Finance de base (SYSCOHADA, facturation et TVA, clients-fournisseurs, trésorerie simple) ; graphe passif alimenté par les événements ; Evidence, Audit et Policy transverses dès la première brique ; API sobre (REST, webhooks, idempotence, bac à sable) ; Country Packs Côte d'Ivoire et Sénégal."],
        ["Construire en lecture seule", "Un agent d'analyse unique (Finance/Direction) ; un à deux copilotes de direction ; AI Gateway avec routage simple et mesure des coûts ; évaluation IA avec jeux de tests métier ; indicateurs de qualité du graphe."],
        ["Différer formellement", "Seize agents réduits à un (les agents en écriture après le jalon J4) ; treize Sector Engines réduits à un pilote de phase 2 ; dix-sept Country Packs réduits à deux ; marketplace après la masse critique ; consolidation, closing avancé et paie complète ; GraphQL et portail public."],
     ]},
    {"t": "h2", "x": "8.3 Pourquoi ce périmètre tient"},
    {"t": "p", "x": "Trois raisons structurelles. D'abord, il est démontrable : chaque jalon de la roadmap se traduit en une scène client observable, pas en un pourcentage d'achèvement interne. Ensuite, il construit l'actif défendable : chaque mois d'utilisation enrichit le graphe et l'historique de preuves, c'est-à-dire l'avantage que la concurrence — y compris les grands modèles généralistes — ne peut pas acheter. Enfin, il retarde les coûts non différenciants : marketplace, treize engines et dix-sept pays consommeraient l'énergie de l'équipe sur des briques dont aucune ne démontre la boucle."},
    {"t": "fig", "path": "fig4_priorisation.png", "caption": "Figure 4 — Priorisation valeur-effort des briques : le quadrant supérieur gauche (victoires rapides) et le noyau structurant définissent la V1 ; la marketplace et les extensions massives relèvent des phases suivantes.", "maxh": 300},
    {"t": "h2", "x": "8.4 Ce que cet audit ne tranche pas"},
    {"t": "p", "x": "Par honnêteté méthodologique, trois décisions relèvent du fondateur et exigent des données de terrain que cet audit ne possède pas : le segment d'ancrage exact (PME formelles de vingt à deux cents salariés, institutions de microfinance, écoles privées, distributeurs), la structure de prix supportable, et le canal de distribution optimal — en particulier le rôle que pourraient jouer les cabinets comptables de la zone comme prescripteurs et opérateurs de premier niveau. L'architecture présentée doit servir ces décisions, pas les précéder : la plus petite boucle démontrable est précisément celle qui permettra de les tester vite et à moindre coût."},
]

CH9 = [
    {"t": "h1", "x": "9. Roadmap priorisée et jalons de décision"},
    {"t": "p", "x": "La roadmap proposée séquence le périmètre du chapitre 8 en trois phases de six à douze mois, chacune fermée par des jalons mesurables de type go/no-go. Leur caractéristique commune est d'être observables du point de vue du client — une scène, un taux, un délai — et non du point de vue interne du projet. Un jalon manqué ne signifie pas l'abandon : il signifie qu'on ne passe pas à la phase suivante tant que la condition de qualité n'est pas remplie, car chaque phase capitalise sur la fiabilité de la précédente."},
    {"t": "table", "title": "Tableau 7 — Roadmap en trois phases avec jalons go/no-go", "widths": [0.15, 0.12, 0.42, 0.31],
     "header": ["Phase", "Période", "Contenu principal", "Jalons mesurables"],
     "aligns": ["l", "c", "l", "l"],
     "rows": [
        ["Phase 1 — Fondation transactionnelle", "M0-M6", "Core réduit avec invariants ; Money sur deux pays avec un fournisseur par corridor ; Finance de base SYSCOHADA ; événements et graphe passif ; Evidence et Audit dès le premier commit ; API interne sobre.", "J1 (M3) : première chaîne facture-encaissement-écriture-preuve sans intervention manuelle. J2 (M6) : réconciliation automatique ≥ 80 % ; deux à trois entreprises pilotes en production réelle."],
        ["Phase 2 — Intelligence en lecture seule", "M6-M12", "Copilote de direction financière et agent analyste en lecture seule ; AI Gateway avec routage et mesure des coûts ; évaluation IA ; un Sector Engine pilote ; conformité DFE ivoirienne ; capture en connectivité dégradée.", "J3 (M9) : 100 % des réponses du copilote avec références de preuve ; adoption hebdomadaire ≥ 60 % des utilisateurs pilotes. J4 (M12) : décision go/no-go sur les agents en écriture, conditionnée au score de qualité du graphe."],
        ["Phase 3 — Expansion contrôlée", "M12-M24", "Agents en écriture plafonnés avec approbation ; API publique et premiers partenaires ; trois à cinq Country Packs additionnels (Bénin, Togo, Cameroun) ; deuxième Sector Engine ; marketplace en bêta fermé.", "J5 : première opération exécutée par un agent avec chaîne de preuve complète et zéro incident sur trois mois. J6 : revenus récurrents couvrant une part définie des coûts d'infrastructure."],
     ]},
    {"t": "h2", "x": "9.1 Les critères de passage, en détail"},
    {"t": "p", "x": "Les seuils proposés méritent d'être explicités, car ils matérialisent la philosophie de l'audit. Le taux de réconciliation automatique d'au moins 80 % au jalon J2 est le symptôme le plus direct de la qualité de la couche Money : en dessous, chaque client pilote devient un coût d'exploitation et un risque de réputation. L'exigence de preuve systématique au jalon J3 — chaque réponse du copilote porte sa référence de pièce — est le test de réalité de la promesse « intelligence ancrée » : s'il échoue, le copilote est un habillage et il faut renforcer le graphe plutôt que le discours. Enfin, la condition de qualité du graphe au jalon J4 protège contre l'erreur la plus coûteuse du projet : donner des pouvoirs d'écriture à des agents qui raisonnent sur des données incomplètes."},
    {"t": "h2", "x": "9.2 Ce que la discipline de séquence protège"},
    {"t": "p", "x": "La structure en trois phases n'est pas une contrainte administrative : elle protège les trois actifs dont dépendra la valeur de YAHRIA à l'horizon de trois ans. La phase 1 protège la donnée — sans opérations captées propres, il n'y a ni graphe ni intelligence crédible. La phase 2 protège la confiance — en n'octroyant des pouvoirs d'action qu'après une preuve statistique de fiabilité, elle évite l'incident fondateur qui ruinerait l'adoption sur un marché où la rumeur décide vite. La phase 3 protège l'économie — en n'ouvrant l'expansion géographique et l'écosystème qu'après la validation du coût de succès, elle évite de répliquer un modèle économique non prouvé sur dix-sept pays."},
    {"t": "stats", "items": [("3", "phases jalonnées"), ("6", "jalons go/no-go mesurables"), ("24", "mois pour la boucle complète prouvée")]},
    {"t": "p", "x": "Le destin de YAHRIA Business OS se jouera moins sur la complétude de son architecture — déjà remarquable — que sur la discipline de sa séquence : capter des données propres, prouver chaque opération, laisser le graphe et les agents grandir sur ce socle. La V1 proposée par cet audit est la plus petite version qui démontre toute la boucle, sur deux pays et un secteur. C'est elle qui rendra, dans l'ordre et en temps voulu, les dix-sept pays, les treize Sector Engines et les seize agents non seulement possibles, mais crédibles — et c'est elle qui transformera le document d'architecture évalué ici en système d'exploitation réellement opérant pour les entreprises africaines."},
]
