# -*- coding: utf-8 -*-
"""Contenu de l'audit YAHRIA BUSINESS OS V1 — Partie A (chapitres 1 à 3)."""

CH1 = [
    {"t": "h1", "x": "1. Synthèse exécutive"},
    {"t": "h2", "x": "1.1 Verdict global"},
    {"t": "p", "x": "Le document « YAHRIA BUSINESS OS V1 » décrit une architecture d'une ambition remarquable : un système d'exploitation d'entreprise africain dans lequel les données deviennent contexte, le contexte alimente un Business Graph, le graphe nourrit une intelligence multi-modèles, l'intelligence déclenche des actions sous contrôle humain, et chaque action produit des preuves auditables. En tant que vision produit, c'est l'une des synthèses les plus cohérentes qu'il soit donné d'évaluer sur ce marché : YAHRIA ne juxtapose pas un ERP et un assistant conversationnel, elle conçoit une boucle opérationnelle fermée (données, intelligence, action, preuve) qui constitue le véritable différenciateur revendiqué. La philosophie « evidence-first » et le placement du Policy Engine au centre de toute exécution sont des choix de conception rares, y compris chez les éditeurs mondiaux."},
    {"t": "p", "x": "En tant que plan de livraison, en revanche, le document présente un problème clair : plus l'architecture est complète, moins elle est livrable. Dix domaines numérotés, vingt-cinq entités dans le seul Core, seize agents spécialisés, treize Sector Engines, dix-sept Country Packs, une marketplace : le périmètre décrit correspond à plusieurs années d'ingénierie pour une équipe produit confirmée. Le document ne mentionne ni l'équipe, ni le budget, ni le calendrier, ni le modèle de revenus. À ce stade « concept détaillé », ce constat n'est pas rédhibitoire — c'est même le meilleur moment pour trancher — mais il impose une hiérarchisation explicite que le document n'opère pas encore. Le présent audit a pour objet de fournir cette hiérarchie, avec un niveau d'exigence volontairement élevé."},
    {"t": "h2", "x": "1.2 Les trois constats structurants"},
    {"t": "p", "x": "<b>Premier constat : la valeur différenciante est concentrée dans la boucle de gouvernance, pas dans l'étendue du catalogue.</b> Ce qui distingue YAHRIA d'un ERP mobile n'est ni le nombre d'agents ni le nombre de pays, mais la séquence intent, Policy Engine, autorisation, contrôle de risque, approbation humaine, exécution, evidence, audit. Cette séquence est décrite une seule fois, alors qu'elle constitue le cœur défendable du produit : elle devrait être le premier objet construit, testé et démontré, brique par brique."},
    {"t": "p", "x": "<b>Deuxième constat : le Business Graph est à la fois la brique la plus différenciante et la plus dépendante.</b> Il ne vaut que ce que valent les données transactionnelles qui l'alimentent. Sur un marché où les données des PME sont fragmentées entre Excel, WhatsApp, caisses manuelles et portefeuilles mobile money dispersés, le graphe ne peut pas être une construction déclarative antérieure aux transactions : il doit être un sous-produit passif des opérations réelles captées par Money et Finance. Le document le laisse deviner sans le formuler ; cette inversion de priorité — capter d'abord, raisonner ensuite — est la plus importante à opérer."},
    {"t": "p", "x": "<b>Troisième constat : le « pour qui d'abord » et le « contre quel revenu » sont absents.</b> Le document traite de manière quasi exhaustive du « comment » technique et reste muet sur le segment d'ancrage, le prix, le coût d'acquisition, le canal de distribution et la concurrence réelle — qui, sur ce marché, est moins un éditeur concurrent que l'ensemble Excel plus comptable plus mobile money. Cette absence n'est pas un détail : elle conditionne l'ordre des priorités plus que toute considération d'architecture, car c'est le segment choisi qui détermine quel sector engine, quel country pack et quel copilote doivent exister en premier."},
    {"t": "h2", "x": "1.3 Recommandation centrale"},
    {"t": "p", "x": "Réduire le périmètre V1 à un noyau transactionnel encadré par la boucle de gouvernance : Core réduit à dix à douze entités, Money avec orchestration et réconciliation, Finance de base alignée sur le référentiel OHADA, Business Graph alimenté passivement par les événements, et agents exclusivement en lecture seule. Deux pays pilotes (Côte d'Ivoire et Sénégal), un seul secteur d'ancrage, la marketplace formellement différée. Le tableau 1 synthétise le verdict par axe d'évaluation, et le chapitre 9 détaille la roadmap correspondante en trois phases jalonnées."},
    {"t": "table", "title": "Tableau 1 — Notation synthétique de l'audit par axe", "widths": [0.30, 0.12, 0.58],
     "header": ["Axe évalué", "Note /10", "Lecture de l'audit"],
     "aligns": ["l", "c", "l"],
     "rows": [
        ["Vision et différenciation", "9", "Boucle données-intelligence-action-preuve réellement distinctive et défendable"],
        ["Architecture et cohérence", "8", "Découpage propre, invariants de données solides, couplages maîtrisés"],
        ["Faisabilité de la V1 en l'état", "3", "Périmètre cinq à dix fois trop large pour un premier cycle de livraison"],
        ["Modèle économique", "2", "Absent du document : segment, prix et coûts non traités"],
        ["Gouvernance et sécurité", "8.5", "Approche evidence-first et policy-first au-dessus des standards du marché"],
     ]},
    {"t": "stats", "items": [("10 → 4", "domaines conservés en V1"), ("16 → 1", "agents, en lecture seule"), ("17 → 2", "Country Packs pilotes")]},
]

CH2 = [
    {"t": "h1", "x": "2. Lecture stratégique de la vision"},
    {"t": "h2", "x": "2.1 Le paradigme revendiqué : de l'outil au système opérant"},
    {"t": "p", "x": "La chaîne de transformation décrite — données, contexte, Business Graph, intelligence, décision, workflow, action, contrôle, evidence — décrit un déplacement de posture bien plus profond qu'une simple intégration d'IA à un logiciel de gestion. L'entreprise ne travaille plus « dans » un outil : l'outil prétend opérer l'entreprise, sous contrôle humain et avec traçabilité. Cette ambition rejoint le mouvement d'agentification engagé par les grands éditeurs mondiaux, mais avec deux choix structurels que la plupart des offres concurrentes n'ont pas faits. D'une part, la preuve systématique : chaque opération produit une evidence référençable, ce qui répond directement aux problèmes de confiance, de contrôle fiscal et de redevabilité vis-à-vis des bailleurs qui structurent le contexte africain. D'autre part, la politique comme première classe : rien ne s'exécute hors Policy Engine, ce qui neutralise le principal reproche fait aux systèmes agentiques, à savoir l'absence de cadre d'autorisation formel."},
    {"t": "p", "x": "Il faut souligner ce que cette promesse implique : un système qui « opère » l'entreprise porte une responsabilité de continuité et d'exactitude sans équivalent dans le logiciel de gestion classique. Un ERP qui tombe en panne est un outil indisponible ; un système opérant qui exécute mal un paiement ou une paie crée un dommage direct. C'est pourquoi l'exigence de fiabilité de la couche transactionnelle de YAHRIA — idempotence, réconciliation, journalisation — n'est pas un détail d'ingénierie mais la condition de légitimité de toute la promesse. L'audit qui suit applique ce principe : chaque brique est évaluée à l'aune de sa contribution à la boucle opérante, non à l'aune de sa complétude fonctionnelle."},
    {"t": "h2", "x": "2.2 Ce que la promesse implique techniquement"},
    {"t": "p", "x": "Pour que le cycle fonctionne, trois conditions doivent être remplies simultanément. Premièrement, un modèle de données unifié où chaque objet métier porte ses invariants de contexte : identifiant de tenant et d'organisation, contexte de politique, références d'audit et de preuve, version et statut. Le document le prévoit dès le Core — c'est un excellent choix, rarement aussi explicite, qui conditionne la possibilité même du graphe et de l'audit sans refonte ultérieure. Deuxièmement, un graphe alimenté passivement par les transactions réelles plutôt que par des déclarations : chaque facture, paiement ou approbation écrit ses nœuds et relations au fil de l'eau. Troisièmement, une exécution strictement encadrée : Execution Fabric avec idempotence, réconciliation systématique et journalisation intégrale. L'architecture mentionne ces trois conditions ; le risque n'est donc pas conceptuel, il réside dans l'ordre de construction et dans la discipline nécessaire pour ne pas disperser l'effort."},
    {"t": "fig", "path": "fig1_architecture.png", "caption": "Figure 1 — Architecture en couches : la plateforme porte le Business OS, les extensions spécialisent le produit ; la gouvernance traverse l'ensemble.", "maxh": 300},
    {"t": "h2", "x": "2.3 Le décalage entre promesse et maturité des données"},
    {"t": "p", "x": "La boucle ne démarre que si YAHRIA capte d'abord des opérations propres. Or les entreprises visées, pour la plupart PME et institutions du continent, opèrent aujourd'hui avec des données fragmentées, tardives et partiellement manuelles. La conséquence stratégique est simple mais non négociable : la V1 doit être, d'abord, un excellent système transactionnel — facturation, encaissement, rapprochement, comptabilité — qui produit des données structurées, avant d'être un système intelligent. Le copilote séduisant présenté en chapitre 10 du document (« Quelle est la situation financière de l'entreprise ? ») ne sera crédible que si les dix-huit mois précédents ont alimenté un graphe fiable. L'ordre « capter, prouver, puis raisonner » doit guider la roadmap ; c'est l'axe central des recommandations de cet audit."},
    {"t": "h2", "x": "2.4 Les forces réelles de la vision"},
    {"t": "bullets", "items": [
        "Evidence-first : transformer chaque opération en preuve horodatée répond au besoin le plus profond du marché — la confiance vérifiable vis-à-vis de l'État, des banques, des bailleurs et des investisseurs.",
        "Policy Engine transversal : le fait que les humains, les agents et les intégrations passent par le même moteur de règles élimine une classe entière de dérives d'autorisation.",
        "Country Packs comme abstraction réglementaire : c'est le bon niveau d'abstraction pour un continent où la fiscalité, la comptabilité (référentiel OHADA) et les moyens de paiement changent à chaque frontière.",
        "Routage multi-modèles avec modèles locaux : l'architecture AI prévoit déjà l'arbitrage coût, latence et confidentialité, ce qui prépare la souveraineté des données sensibles.",
    ]},
    {"t": "p", "x": "Ces quatre forces forment un ensemble cohérent : elles ne concernent aucune fonctionnalité spectaculaire, mais toutes les conditions de confiance qui décideront de l'adoption réelle. L'audit des chapitres suivants montre néanmoins que la valeur de ces choix ne se réalisera que si le périmètre de la V1 est drastiquement resserré autour d'elles."},
]

CH3 = [
    {"t": "h1", "x": "3. Audit des fondations transactionnelles"},
    {"t": "h2", "x": "3.1 Le Core — discipline exemplaire, périmètre à tailler"},
    {"t": "p", "x": "Le principe le plus précieux du document se trouve dans le Core : l'ensemble des invariants attachés à tout objet métier (tenant_id, organization_id, entity_id, created_by, created_at, updated_at, status, version, policy_context, audit_reference, evidence_reference). Cette discipline de données est ce qui rendra possible, des années plus tard, le graphe, l'audit et les agents sans migration douloureuse. Elle doit être considérée comme non négociable et vérifiée par des tests automatiques dès la première ligne de code."},
    {"t": "p", "x": "En revanche, la liste des vingt-cinq agrégats du Core — organisations, entités légales, succursales, départements, espaces de travail, clients, fournisseurs, employés, partenaires, produits, services, contrats, documents, tâches, workflows, approbations, notifications, calendrier, communication, règles métier, événements — revient à construire un ERP généraliste complet avant le premier client. Chaque agrégat implique son cycle de vie, ses politiques, ses interfaces et ses tests. L'audit recommande de figer les invariants (ils sont transverses et peu coûteux) mais de réduire les entités de la V1 aux dix à douze réellement nécessaires au cycle « facture à encaissement » et au cycle « demande d'achat à paiement ». Les entités restantes suivront la demande réelle des clients pilotes, pas l'inventaire conceptuel."},
    {"t": "h2", "x": "3.2 Money — le vrai produit dur"},
    {"t": "p", "x": "La couche Money est la brique la plus exigeante techniquement et celle où YAHRIA se jouera sa crédibilité : un paiement perdu ou dupliqué détruit instantanément la confiance qu'une promesse « evidence-first » cherche à établir. L'orchestration décrite — choix du moyen, du fournisseur, du compte, évaluation du risque, autorisation, justification, réconciliation — est exactement la bonne ambition, et la présence explicite de l'idempotence et du failover témoigne d'une compréhension réelle des paiements. C'est la partie la plus difficile et la plus différenciante de Money, bien au-delà d'un simple agrégateur."},
    {"t": "p", "x": "Le document sous-estime toutefois la dépendance critique de cette brique : les intégrations mobile money et bancaires de la zone (Orange Money, Wave, MTN MoMo, Moov, et les canaux bancaires UEMOA) sont hétérogènes, souvent sans environnement de bac à sable stable, avec des latences, des codes d'erreur et des ruptures de service non documentés. Ce n'est pas un problème de code : c'est un problème d'opérations, de partenariats et de surveillance continue. L'audit recommande un ledger interne faisant foi, une file de réconciliation quotidienne systématique, une abstraction de fournisseur de paiement conçue dès le départ, et un doublement de fournisseur sur les corridors critiques des deux pays pilotes."},
    {"t": "h2", "x": "3.3 Finance — ambition comptable réelle, complexité sous-estimée"},
    {"t": "p", "x": "Le squelette décrit — facture, client, encaissement, réconciliation, comptabilité, trésorerie, prévision — est le bon, et l'articulation Finance-Money-Graph-AI crée l'assise exacte du futur copilote de direction financière. La liste des capacités inclut cependant le closing, la consolidation, le multi-devises et le multi-entités : ce sont des modules de niveau groupe, dont chacun constitue un projet en soi (consolidation conforme aux normes, clôture assistée multi-pays). Les traiter comme des cases de la même liste revient à masquer plusieurs années d'effort."},
    {"t": "p", "x": "Pour la V1, l'audit recommande un périmètre comptable précis : plan comptable SYSCOHADA révisé (le référentiel OHADA commun à la majorité des pays visés), facturation conforme aux exigences locales — dont la facture électronique obligatoire en Côte d'Ivoire —, TVA par pays, journaux, comptes clients et fournisseurs, et une trésorerie simple. La clôture assistée, la consolidation et la prévision appartiennent aux cycles suivants, une fois que les écritures de base sont fiables et que la réconciliation fonctionne à un taux élevé."},
    {"t": "h2", "x": "3.4 Procurement et People — justifiés, mais qui élargissent encore le périmètre"},
    {"t": "p", "x": "L'ajout de ces deux domaines au Business OS est logique : une entreprise opère aussi ses achats et son personnel, et la chaîne People, Payroll, Money, Finance, Accounting est correctement branchée. L'audit note toutefois que la paie est l'un des domaines de conformité les plus sensibles qui soient — caisses sociales, barèmes fiscaux et déclaratifs propres à chaque pays — et que le domaine des dépenses et avances des employés en rapproche la complexité. Pour la V1, People devrait se limiter au registre des employés et au rattachement aux workflows d'approbation ; la paie complète devrait être différée d'au moins un cycle produit, ou fournie via un partenaire intégré. Procurement devrait se limiter à la séquence demande, bon de commande, réception — les modules de qualification fournisseurs et d'intelligence d'achat relevant de la phase d'expansion."},
    {"t": "table", "title": "Tableau 2 — Verdict sur les fondations transactionnelles", "widths": [0.16, 0.28, 0.30, 0.26],
     "header": ["Brique", "Force principale", "Limite critique", "Décision V1 recommandée"],
     "aligns": ["l", "l", "l", "l"],
     "rows": [
        ["00 Core", "Invariants de métadonnées exemplaires, transverses", "25 entités = abstraction prématurée, coût d'ingénierie diffus", "Figer les invariants ; réduire à 10-12 entités"],
        ["01 Money", "Orchestration, idempotence, réconciliation différenciantes", "Dépendance aux intégrations mobile money et bancaires instables", "Cœur dur de la V1 ; ledger interne ; deux fournisseurs par corridor"],
        ["02 Finance", "Cycle facture-comptabilité-trésorerie bien articulé", "Closing, consolidation et multi-entités = projets distincts", "SYSCOHADA de base, TVA, clients/fournisseurs ; consolidation différée"],
        ["Procurement", "Chaîne d'achat complète et bien séquencée", "Un domaine entier de plus dans le périmètre initial", "Demande, bon de commande, réception uniquement"],
        ["People", "Chaîne paie correctement branchée sur Money et Finance", "Conformité paie très sensible et variable par pays", "Registre employés et approbations ; paie différée ou partenaire"],
     ]},
]
